apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: flask-app-scaler
spec:
  scaleTargetRef:
    name: flask-app
  minReplicaCount: 2
  maxReplicaCount: 5
  pollingInterval: 15
  cooldownPeriod: 30
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-server.monitoring.svc.cluster.local
      metricName: http_requests_total
      threshold: '50'
      query: sum(rate(http_requests_total{app="flask"}[2m])) / count(count(http_requests_total) by (pod))