apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: flask
  endpoints:
  - port: http
    interval: 15s
  namespaceSelector:
    matchNames:
    - default